environmentVars:
  - name: VAULT_ADDRESS
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: HOST
  - name: VAULT_ROLE_ID
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: VAULT_ROLE_ID
  - name: OPERATOR_SECRET_ID
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: OPERATOR_SECRET_ID
  - name: VAULT_TOKEN_MAX_TTL
    valueFrom:
      secretKeyRef:
        name: vault-secret
        key: OPERATOR_TOKEN_TTL