on:
  push:
    paths:
      - 'chart/**'
    branches: [ main ]

jobs:
  deploy_universal:
    uses: flmorg/universal-workflows/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
      chartRepo: oci://ghcr.io/flmorg
      chartName: universal-chart
      version: ^1.0.0
    secrets: inherit

  deploy_external:
    needs: [ deploy_universal ]
    uses: flmorg/universal-workflows/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
      chartRepo: https://ricoberger.github.io/helm-charts
      chartName: vault-secrets-operator
      version: ^1.0.0